Manual exposure
luxonis/depthai-ros pull request #136
Opened 2022-09-04 07:44 UTC by nindanaoto

I added manual exposure setting functionality for ROS1's stero_inertial_node because this functionality is needed to use OAK-D in the out-door environment.

2022-09-04 12:35 UTC, saching13 reviewed
Thanks. Would it be possible to copy paste the same into ros2 one.? Prefer to keep them identical.

2022-09-04 16:26 UTC, nindanaoto commented
I'm planning to do that. I have no daily-use environment for ROS2, so I'm constricting it to test ROS2 codes.......

2022-09-04 22:42 UTC, saching13 commented
No worries. We can test it before merging.

2022-09-07 18:14 UTC, saching13 commented
@daxoft  can you test the both of them please?

2022-09-07 18:17 UTC, saching13 requested changes
Thanks for the PR. 
Can you also add launch file argument to  `stereo_inertial_node.launch.py` ?

2022-09-07 18:17 UTC, saching13 commented on depthai_examples/launch/stereo_inertial_node.launch
> -    <arg name="syncNN"                 default="true" />
any reason for tuning them off by default ?

2022-09-07 18:17 UTC, saching13 commented on depthai_examples/ros2_src/stereo_inertial_publisher.cpp
> +    node->declare_parameter("manualExposure", true);
Can you set it to false here by default?

2022-09-08 10:13 UTC, daxoft commented
> @daxoft can you test the both of them please?

it's working for both, I can push the launch update for ros2 after it's merged if needed

2022-09-10 06:41 UTC, nindanaoto commented
@saching13 
The change of the launch file you mentioned is my failure. These change is just needed for checking the manual Exposure functionality in my environment, so I force pushed to revert unnecessary change of the launch file.
I fixed Python script but not yet tested.

2022-09-23 05:38 UTC, nindanaoto commented
@saching13 How about the current version?

2022-09-27 17:11 UTC, saching13 commented
@nindanaoto  all looks good. Thanks for the contribution.  
@daxoft  Can you test on ROS2 with the launch file and we can go ahead with the merge.

2022-10-03 22:07 UTC, saching13 commented
cc: @daxoft  bumping this.

2022-10-03 23:02 UTC, daxoft commented
@saching13 tested for ros and ros2, works with foxy, galactic and noetic ros distros
 @nindanaoto thank you for your contribution!

2022-10-03 23:14 UTC, merged