Add custom metadata message for lens position (this time to correct branch)
luxonis/depthai-ros pull request #73
Opened 2022-02-21 22:43 UTC by jdavidberger

Also threw in everything available on an ImgFrame.

Note that I could not test on ROS2.

2022-02-21 22:53 UTC, saching13 commented
```
  Error processing 'float32 LensPosition' of
  'depthai_ros_msgs/CameraMetadata': ''LensPosition' is an invalid field
  name.  It should have the pattern '^(?!.*__)(?!.*_$)[a-z][a-z0-9_]*$''

```

Can you change the field names to `snake_case` ? PascalCase doesn't satisfy ros2 convention.

2022-02-22 03:02 UTC, saching13 requested changes
I think after adding the ROS2 header we are good to merge.

2022-02-22 03:02 UTC, saching13 commented on depthai_bridge/include/depthai_bridge/BridgePublisher.hpp
> +    #include "depthai_ros_msgs/CameraMetadata.h"
Can you add this to `#ifdef IS_ROS2` part ?
`#include "depthai_ros_msgs/msg/CameraMetadata.hpp"`

2022-02-22 03:28 UTC, jdavidberger commented
I have another larger PR that I'm going to push in a little bit; is there a quick ROS2 check docker build or something I could run to sanity check?

2022-02-24 18:34 UTC, merged